version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: tinx
    main: ./cmd/tinx
    binary: tinx
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/sourceplane/tinx/pkg/version.Version={{ .Version }}

archives:
  - id: tinx-archive
    ids:
      - tinx
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: checksums.txt

changelog:
  use: git
